<?php
/**
 * GENERATED FILE - DO NOT EDIT.
 *
 * Regenerate with: composer extract
 *
 * source:    woocommerce/action-scheduler
 * version:   4.0.0
 * generated: 2026-07-29
 */

return array(
	'exclude-classes' => array(
		'ActionScheduler',
		'ActionScheduler_Abstract_ListTable',
		'ActionScheduler_Abstract_QueueRunner',
		'ActionScheduler_Abstract_QueueRunner_Deprecated',
		'ActionScheduler_Abstract_RecurringSchedule',
		'ActionScheduler_Abstract_Schedule',
		'ActionScheduler_Abstract_Schema',
		'ActionScheduler_Action',
		'ActionScheduler_ActionClaim',
		'ActionScheduler_ActionFactory',
		'ActionScheduler_AdminView',
		'ActionScheduler_AdminView_Deprecated',
		'ActionScheduler_AsyncRequest_QueueRunner',
		'ActionScheduler_CanceledAction',
		'ActionScheduler_CanceledSchedule',
		'ActionScheduler_Compatibility',
		'ActionScheduler_CronSchedule',
		'ActionScheduler_DBLogger',
		'ActionScheduler_DBStore',
		'ActionScheduler_DBStoreMigrator',
		'ActionScheduler_DataController',
		'ActionScheduler_DateTime',
		'ActionScheduler_Exception',
		'ActionScheduler_FatalErrorMonitor',
		'ActionScheduler_FinishedAction',
		'ActionScheduler_HybridStore',
		'ActionScheduler_IntervalSchedule',
		'ActionScheduler_InvalidActionException',
		'ActionScheduler_ListTable',
		'ActionScheduler_Lock',
		'ActionScheduler_LogEntry',
		'ActionScheduler_Logger',
		'ActionScheduler_LoggerSchema',
		'ActionScheduler_NullAction',
		'ActionScheduler_NullLogEntry',
		'ActionScheduler_NullSchedule',
		'ActionScheduler_OptionLock',
		'ActionScheduler_QueueCleaner',
		'ActionScheduler_QueueRunner',
		'ActionScheduler_RecurringActionScheduler',
		'ActionScheduler_Schedule',
		'ActionScheduler_Schedule_Deprecated',
		'ActionScheduler_SimpleSchedule',
		'ActionScheduler_Store',
		'ActionScheduler_StoreSchema',
		'ActionScheduler_Store_Deprecated',
		'ActionScheduler_SystemInformation',
		'ActionScheduler_TimezoneHelper',
		'ActionScheduler_Versions',
		'ActionScheduler_WPCLI_Clean_Command',
		'ActionScheduler_WPCLI_Command',
		'ActionScheduler_WPCLI_QueueRunner',
		'ActionScheduler_WPCLI_Scheduler_command',
		'ActionScheduler_WPCommentCleaner',
		'ActionScheduler_wcSystemStatus',
		'ActionScheduler_wpCommentLogger',
		'ActionScheduler_wpPostStore',
		'ActionScheduler_wpPostStore_PostStatusRegistrar',
		'ActionScheduler_wpPostStore_PostTypeRegistrar',
		'ActionScheduler_wpPostStore_TaxonomyRegistrar',
		'CronExpression',
		'CronExpression_AbstractField',
		'CronExpression_DayOfMonthField',
		'CronExpression_DayOfWeekField',
		'CronExpression_FieldFactory',
		'CronExpression_FieldInterface',
		'CronExpression_HoursField',
		'CronExpression_MinutesField',
		'CronExpression_MonthField',
		'CronExpression_YearField',
		'WP_Async_Request',
	),
	'exclude-constants' => array(
	),
	'exclude-functions' => array(
		'action_scheduler_initialize_4_dot_0_dot_0',
		'action_scheduler_register_4_dot_0_dot_0',
		'as_enqueue_async_action',
		'as_get_datetime_object',
		'as_get_scheduled_actions',
		'as_has_scheduled_action',
		'as_next_scheduled_action',
		'as_schedule_cron_action',
		'as_schedule_recurring_action',
		'as_schedule_single_action',
		'as_supports',
		'as_unschedule_action',
		'as_unschedule_all_actions',
		'wc_get_scheduled_actions',
		'wc_next_scheduled_action',
		'wc_schedule_cron_action',
		'wc_schedule_recurring_action',
		'wc_schedule_single_action',
		'wc_unschedule_action',
	),
	'exclude-namespaces' => array(
		'Action_Scheduler\\Migration',
		'Action_Scheduler\\WP_CLI',
		'Action_Scheduler\\WP_CLI\\Action',
	),
);
