<?php return array (
  'exclude-namespaces' => 
  array (
    0 => 'WP_CLI\\Tests\\Traverser',
    1 => 'WP_CLI\\Tests\\CSV',
    2 => 'WpOrg\\Requests',
    8 => 'WpOrg\\Requests\\Transport',
    10 => 'WpOrg\\Requests\\Response',
    11 => 'WpOrg\\Requests\\Proxy',
    13 => 'WpOrg\\Requests\\Auth',
    23 => 'WpOrg\\Requests\\Cookie',
    25 => 'WpOrg\\Requests\\Exception\\Transport',
    26 => 'WpOrg\\Requests\\Exception',
    30 => 'WpOrg\\Requests\\Exception\\Http',
    63 => 'WpOrg\\Requests\\Utility',
    66 => 'WP_CLI',
    68 => 'WP_CLI\\Loggers',
    72 => 'WP_CLI\\Context',
    76 => 'WP_CLI\\Bootstrap',
    100 => 'WP_CLI\\Fetchers',
    106 => 'WP_CLI\\Traverser',
    108 => 'WP_CLI\\Dispatcher',
    126 => 'WP_CLI\\Exception',
    132 => 'WP_CLI\\Iterators',
    142 => 'WP_CLI\\Utils',
  ),
  'exclude-classes' => 
  array (
    0 => 'WpOrgApiTest',
    1 => 'InflectorTest',
    2 => 'SynopsisParserTest',
    3 => 'ProcessTest',
    4 => 'UtilsTest',
    5 => 'Mock_Requests_Transport',
    6 => 'FileCacheTest',
    7 => 'MockRegularLogger',
    8 => 'MockQuietLogger',
    9 => 'LoggingTest',
    10 => 'ConfiguratorTest',
    11 => 'DocParserTest',
    12 => 'WPVersionCompareTest',
    13 => 'ArgValidationTest',
    14 => 'WPCLITest',
    15 => 'ExtractorTest',
    16 => 'CommandFactoryTests_Get_Doc_Comment_1_Command',
    17 => 'CommandFactoryTests_Get_Doc_Comment_2_Command',
    18 => 'CommandFactoryTests_Get_Doc_Comment_1_Command_Win',
    19 => 'CommandFactoryTests_Get_Doc_Comment_2_Command_Win',
    20 => 'CommandFactoryTest',
    21 => 'HelpTest',
    22 => 'Requests',
    23 => 'WP_CLI',
    24 => 'WP_CLI_Command',
    25 => 'CLI_Command',
    26 => 'Help_Command',
    27 => 'CLI_Cache_Command',
    28 => 'CLI_Alias_Command',
  ),
  'exclude-constants' => 
  array (
    0 => 'WP_CLI_ROOT',
    1 => 'WP_CLI_VENDOR_DIR',
    3 => 'REQUESTS_SILENCE_PSR0_DEPRECATIONS',
    4 => 'REQUESTS_AUTOLOAD_REGISTERED',
    6 => 'WP_ADMIN',
    8 => 'ABSPATH',
    9 => 'WP_INSTALLING',
    11 => 'COOKIEHASH',
    12 => 'WP_LOAD_IMPORTERS',
    13 => 'WP_IMPORTING',
    14 => 'DOING_CRON',
    16 => 'WP_DEBUG',
    17 => 'WP_DEBUG_DISPLAY',
    19 => 'WPINC',
    20 => 'MULTISITE',
    21 => 'WP_CLI',
    22 => 'WP_CLI_VERSION',
    23 => 'WP_CLI_START_MICROTIME',
  ),
  'exclude-functions' => 
  array (
    0 => 'commandfactorytests_get_doc_comment_func_1_win',
    1 => 'commandfactorytests_get_doc_comment_func_2_win',
    2 => 'commandfactorytests_get_doc_comment_func_1',
    3 => 'commandfactorytests_get_doc_comment_func_2',
    4 => 'ini_set',
    5 => 'get_magic_quotes_gpc',
  ),
);